import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer"
import type { GeneratedMeal } from "@/lib/mealDatabase"
import type { ProjectedWeek } from "@/lib/nutrition"
import { kgToLb } from "@/lib/unitConversion"

const colors = {
  green: "#639922",
  teal: "#1D9E75",
  light: "#f0f7e6",
  gray: "#6b7280",
  dark: "#1f2937",
  white: "#ffffff",
  border: "#e5e7eb",
}

const styles = StyleSheet.create({
  page: { fontFamily: "Helvetica", fontSize: 10, color: colors.dark, padding: 40 },
  coverPage: { fontFamily: "Helvetica", justifyContent: "center", alignItems: "center", padding: 60 },
  logo: { fontSize: 28, fontFamily: "Helvetica-Bold", color: colors.green, marginBottom: 8 },
  coverTitle: { fontSize: 20, fontFamily: "Helvetica-Bold", color: colors.dark, marginBottom: 6, textAlign: "center" },
  coverSub: { fontSize: 12, color: colors.gray, textAlign: "center", marginBottom: 4 },
  section: { marginBottom: 16 },
  h1: { fontSize: 14, fontFamily: "Helvetica-Bold", color: colors.green, marginBottom: 8 },
  h2: { fontSize: 11, fontFamily: "Helvetica-Bold", color: colors.dark, marginBottom: 5 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 160, color: colors.gray, fontSize: 9 },
  value: { flex: 1, fontFamily: "Helvetica-Bold", fontSize: 9 },
  table: { borderWidth: 1, borderColor: colors.border, borderRadius: 4, overflow: "hidden", marginBottom: 8 },
  thead: { flexDirection: "row", backgroundColor: colors.light, padding: "6 8", borderBottomWidth: 1, borderBottomColor: colors.border },
  th: { flex: 1, fontSize: 8, fontFamily: "Helvetica-Bold", color: colors.gray },
  tbody: {},
  tr: { flexDirection: "row", padding: "5 8", borderBottomWidth: 1, borderBottomColor: colors.border },
  td: { flex: 1, fontSize: 8, color: colors.dark },
  tdRight: { flex: 1, fontSize: 8, color: colors.dark, textAlign: "right" },
  pill: { backgroundColor: colors.light, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginBottom: 8 },
  pillText: { color: colors.green, fontSize: 9, fontFamily: "Helvetica-Bold" },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 7,
    color: colors.gray,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 6,
  },
  divider: { height: 1, backgroundColor: colors.border, marginBottom: 12 },
  badge: { flexDirection: "row", gap: 16, marginBottom: 10 },
  badgeItem: { alignItems: "center" },
  badgeVal: { fontSize: 14, fontFamily: "Helvetica-Bold", color: colors.green },
  badgeLabel: { fontSize: 7, color: colors.gray },
})

const Footer = () => (
  <Text style={styles.footer} fixed>
    Generated by NutriPlan · Not a substitute for professional medical advice
  </Text>
)

interface PDFProps {
  profile: { name: string; gender: string; weight_kg: number; target_weight_kg: number; goal_days: number; unit_preference: string }
  plan: { bmr: number; tdee: number; target_calories: number; daily_deficit: number; protein_g: number; carbs_g: number; fat_g: number; plan_json: { bmi: number; bmiCategory: string; estimatedWeeklyLoss_kg: number; projectedWeights: ProjectedWeek[] } }
  meals: GeneratedMeal[]
}

export default function MealPlanPDF({ profile, plan, meals }: PDFProps) {
  const unit = profile.unit_preference
  const cv = (kg: number) => unit === "imperial" ? `${kgToLb(kg).toFixed(1)} lb` : `${kg.toFixed(1)} kg`

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={[styles.page, styles.coverPage]}>
        <Text style={styles.logo}>NutriPlan</Text>
        <Text style={styles.coverTitle}>{profile.name}'s Personalized Meal Plan</Text>
        <Text style={styles.coverSub}>
          Generated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
        </Text>
        <Text style={styles.coverSub}>
          Goal: {cv(profile.target_weight_kg)} in {profile.goal_days} days
        </Text>
        <View style={{ marginTop: 30 }}>
          <Text style={styles.coverSub}>Starting weight: {cv(profile.weight_kg)}</Text>
          <Text style={styles.coverSub}>
            Estimated weekly loss: {unit === "imperial"
              ? `${(plan.plan_json.estimatedWeeklyLoss_kg * 2.20462).toFixed(1)} lb`
              : `${plan.plan_json.estimatedWeeklyLoss_kg.toFixed(2)} kg`}
          </Text>
        </View>
        <Footer />
      </Page>

      {/* Metrics Page */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Your Key Metrics</Text>
        <View style={styles.badge}>
          {[
            { label: "BMR", value: `${plan.bmr} kcal` },
            { label: "TDEE", value: `${plan.tdee} kcal` },
            { label: "Target Calories", value: `${plan.target_calories} kcal` },
            { label: "Daily Deficit", value: `${plan.daily_deficit} kcal` },
          ].map((b) => (
            <View key={b.label} style={styles.badgeItem}>
              <Text style={styles.badgeVal}>{b.value}</Text>
              <Text style={styles.badgeLabel}>{b.label}</Text>
            </View>
          ))}
        </View>

        <View style={styles.divider} />

        <Text style={styles.h2}>Macronutrient Targets</Text>
        {[
          ["Protein", `${plan.protein_g}g`, "30% of calories / ≥0.8g per lb body weight"],
          ["Carbohydrates", `${plan.carbs_g}g`, "40% of calories"],
          ["Fat", `${plan.fat_g}g`, "30% of calories"],
        ].map(([label, val, note]) => (
          <View key={label} style={styles.row}>
            <Text style={styles.label}>{label}</Text>
            <Text style={styles.value}>{val}</Text>
            <Text style={{ ...styles.td, color: colors.gray }}>{note}</Text>
          </View>
        ))}

        <View style={[styles.divider, { marginTop: 8 }]} />

        <Text style={styles.h2}>Body Composition</Text>
        <View style={styles.row}><Text style={styles.label}>BMI</Text><Text style={styles.value}>{plan.plan_json.bmi} ({plan.plan_json.bmiCategory})</Text></View>
        <View style={styles.row}><Text style={styles.label}>Current Weight</Text><Text style={styles.value}>{cv(profile.weight_kg)}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Target Weight</Text><Text style={styles.value}>{cv(profile.target_weight_kg)}</Text></View>
        <Footer />
      </Page>

      {/* One page per meal */}
      {meals.map((meal) => (
        <Page key={meal.mealName} size="A4" style={styles.page}>
          <View style={styles.pill}>
            <Text style={styles.pillText}>{meal.mealName} · {meal.mealTime}</Text>
          </View>
          <View style={styles.badge}>
            {[
              { label: "Calories", value: `${meal.actualCalories} kcal` },
              { label: "Protein", value: `${meal.protein_g}g` },
              { label: "Carbs", value: `${meal.carbs_g}g` },
              { label: "Fat", value: `${meal.fat_g}g` },
            ].map((b) => (
              <View key={b.label} style={styles.badgeItem}>
                <Text style={styles.badgeVal}>{b.value}</Text>
                <Text style={styles.badgeLabel}>{b.label}</Text>
              </View>
            ))}
          </View>

          <View style={styles.table}>
            <View style={styles.thead}>
              <Text style={{ ...styles.th, flex: 3 }}>Food Item</Text>
              <Text style={{ ...styles.th, textAlign: "right" }}>Amount</Text>
              <Text style={{ ...styles.th, textAlign: "right" }}>Cal</Text>
              <Text style={{ ...styles.th, textAlign: "right" }}>Protein</Text>
              <Text style={{ ...styles.th, textAlign: "right" }}>Carbs</Text>
              <Text style={{ ...styles.th, textAlign: "right" }}>Fat</Text>
            </View>
            {meal.foods.map((food) => (
              <View key={food.id} style={styles.tr}>
                <Text style={{ ...styles.td, flex: 3 }}>{food.name}</Text>
                <Text style={styles.tdRight}>
                  {unit === "imperial"
                    ? `${Math.round((food.scaledGrams / 28.35) * 10) / 10} oz`
                    : `${food.scaledGrams}g`}
                </Text>
                <Text style={styles.tdRight}>{food.scaledCalories}</Text>
                <Text style={styles.tdRight}>{food.scaledProtein_g}g</Text>
                <Text style={styles.tdRight}>{food.scaledCarbs_g}g</Text>
                <Text style={styles.tdRight}>{food.scaledFat_g}g</Text>
              </View>
            ))}
          </View>
          <Footer />
        </Page>
      ))}

      {/* Progress Timeline Table */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Projected Weight Timeline</Text>
        <View style={styles.table}>
          <View style={styles.thead}>
            <Text style={styles.th}>Week</Text>
            <Text style={styles.th}>Date</Text>
            <Text style={{ ...styles.th, textAlign: "right" }}>Weight</Text>
            <Text style={{ ...styles.th, flex: 2 }}>Milestone</Text>
          </View>
          {plan.plan_json.projectedWeights.map((w) => (
            <View key={w.week} style={styles.tr}>
              <Text style={styles.td}>Week {w.week}</Text>
              <Text style={styles.td}>
                {new Date(w.date).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
              </Text>
              <Text style={styles.tdRight}>{cv(w.projectedWeight_kg)}</Text>
              <Text style={{ ...styles.td, flex: 2, color: colors.teal }}>{w.milestone || ""}</Text>
            </View>
          ))}
        </View>
        <Footer />
      </Page>

      {/* Science Summary */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Scientific Basis</Text>
        {[
          ["BMR Formula", "Mifflin-St Jeor equation (1990). Men: (10×kg)+(6.25×cm)−(5×age)+5. Women: same −161."],
          ["TDEE", "BMR × activity factor (1.2–1.9 based on exercise frequency and intensity)."],
          ["Caloric Deficit", "~7,700 kcal per kg of fat loss (Wishnofsky Rule). Max safe deficit: 1,000 kcal/day."],
          ["Macros", "Protein 30% / Carbs 40% / Fat 30%. Min protein: 0.8g per lb body weight."],
          ["BMI", "WHO classification: <18.5 Underweight | 18.5–24.9 Normal | 25–29.9 Overweight | ≥30 Obese"],
          ["Safety", "Min 1,200 kcal/day (women) or 1,500 kcal/day (men). Deficit never exceeds 1,000 kcal/day."],
        ].map(([title, body]) => (
          <View key={title} style={{ marginBottom: 10 }}>
            <Text style={styles.h2}>{title}</Text>
            <Text style={{ fontSize: 9, color: colors.gray, lineHeight: 1.5 }}>{body}</Text>
          </View>
        ))}
        <View style={{ marginTop: 10 }}>
          <Text style={{ fontSize: 8, color: colors.gray }}>
            Sources: Mifflin MD et al., Am J Clin Nutr 1990; Wishnofsky M, Am J Clin Nutr 1958; WHO Technical Report Series 894, 2000.
          </Text>
        </View>
        <Footer />
      </Page>
    </Document>
  )
}
