import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"
import type { ShoppingCategory, ShoppingItem } from "@/lib/mealDatabase"

const colors = {
  green: "#639922",
  gray: "#6b7280",
  dark: "#1f2937",
  border: "#e5e7eb",
  light: "#f0f7e6",
}

const styles = StyleSheet.create({
  page: { fontFamily: "Helvetica", fontSize: 10, color: colors.dark, padding: 40 },
  header: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: colors.border, paddingBottom: 12 },
  logo: { fontSize: 18, fontFamily: "Helvetica-Bold", color: colors.green, marginBottom: 4 },
  title: { fontSize: 14, fontFamily: "Helvetica-Bold", color: colors.dark },
  sub: { fontSize: 9, color: colors.gray, marginTop: 2 },
  category: { marginBottom: 14 },
  categoryHeader: { backgroundColor: colors.light, padding: "6 8", marginBottom: 6, borderRadius: 3 },
  categoryTitle: { fontSize: 10, fontFamily: "Helvetica-Bold", color: colors.green },
  item: { flexDirection: "row", alignItems: "center", paddingVertical: 4, paddingHorizontal: 8, borderBottomWidth: 1, borderBottomColor: colors.border },
  checkbox: { width: 10, height: 10, borderWidth: 1, borderColor: colors.gray, marginRight: 8, borderRadius: 2 },
  itemName: { flex: 1, fontSize: 9 },
  itemQty: { fontSize: 9, color: colors.gray, textAlign: "right", minWidth: 70 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 7,
    color: colors.gray,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 6,
  },
})

interface ShoppingListPDFProps {
  list: Record<ShoppingCategory, ShoppingItem[]>
  period: "weekly" | "monthly"
  userName: string
}

const CATEGORY_EMOJI: Record<ShoppingCategory, string> = {
  Proteins: "🥩",
  "Carbohydrates & Grains": "🌾",
  Dairy: "🥛",
  "Fruits & Vegetables": "🥦",
  "Healthy Fats": "🥑",
  Other: "📦",
}

export default function ShoppingListPDF({ list, period, userName }: ShoppingListPDFProps) {
  const categories = Object.keys(list) as ShoppingCategory[]

  const formatQty = (qty: number, unit: string) => {
    if (unit === "grams") return `${qty}g`
    if (unit === "ml") return `${qty} ml`
    return `${qty} ${unit}`
  }

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.logo}>NutriPlan</Text>
          <Text style={styles.title}>{userName}'s Shopping List</Text>
          <Text style={styles.sub}>
            {period === "monthly" ? "Monthly" : "Weekly"} · {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
            {period === "monthly" && " · Quantities = weekly × 4.3"}
          </Text>
        </View>

        {/* Categories */}
        {categories.map((cat) => {
          const items = list[cat]
          if (!items || items.length === 0) return null
          return (
            <View key={cat} style={styles.category} wrap={false}>
              <View style={styles.categoryHeader}>
                <Text style={styles.categoryTitle}>{cat}</Text>
              </View>
              {items.map((item, i) => (
                <View key={i} style={styles.item}>
                  <View style={styles.checkbox} />
                  <Text style={styles.itemName}>{item.name}</Text>
                  <Text style={styles.itemQty}>{formatQty(item.quantity, item.unit)}</Text>
                </View>
              ))}
            </View>
          )
        })}

        <Text style={styles.footer}>
          Generated by NutriPlan · Not a substitute for professional medical advice · Quantities are estimates
        </Text>
      </Page>
    </Document>
  )
}
